### PR TITLE
Burst id and absolute orbit number

### PR DESCRIPTION
**Pull request by seongsujeong**
This PR updates the two things:

- Burst ID: three digits for the track number. e.g. `t051_`, `t123_`
- Absolute orbit number: For populating the RTC metadata, `Sentinel1BurstSlc` will keep the absolute orbit number as one of its attributes.

### CODE REVIEW

**Review by gshiroma — APPROVED** [review]
LGTM, as long as the changes are OK with @hfattahi , @LiangJYu , and @vbrancat

**Comment by LiangJYu** [comment]
Before approving, may I ask what are the use cases for these changes?

**Comment by seongsujeong** [comment]
> Before approving, may I ask what are the use cases for these changes?

Yes. The new format of burst_id will make the lengths of the string to be the same.
RTC metadata parses some information from burst id. We can already extract what we need from the current format, but the new one will make it easier.
Regarding the absolute orbit number, we need this information to make the RTC metadata as similar as the  NISAR-equivalent product (GCOV)

**Review by LiangJYu — COMMENTED** [review]
@seongsujeong Thank you for the expanded explanation.

The unit tests need to be fixed to account for these changes by:
1. updating `burst_id` format [here](https://github.com/opera-adt/s1-reader/blob/142ece4672f005ce2e1e7a9fd562dceed187e14e/tests/test_bursts.py#L31).
2. adding an `assert` for `abs_orbit_number` [here](https://github.com/opera-adt/s1-reader/blob/142ece4672f005ce2e1e7a9fd562dceed187e14e/tests/test_bursts.py#L34)

**Comment by seongsujeong** [comment]
@LiangJYu Thanks for pointing me to the unit test. I've updated `test_bursts.py` in accordance with your suggestion. 
Currently circieCI keeps on failing due to the error message below:

```
CondaHTTPError: HTTP 404 NOT FOUND for url <https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.12-h7f8727e_1.conda>
Elapsed: 00:00.093111
CF-RAY: 740068947daf5b28-IAD

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.



Exited with code exit status 1
CircleCI received exit code 1
```

Hope this failure is not related to this PR.

**Review by LiangJYu — APPROVED** [review]
LGTM

**Comment by LiangJYu** [comment]
> @LiangJYu Thanks for pointing me to the unit test. I've updated `test_bursts.py` in accordance with your suggestion. Currently circieCI keeps on failing due to the error message below:
> 
> ```
> CondaHTTPError: HTTP 404 NOT FOUND for url <https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.12-h7f8727e_1.conda>
> Elapsed: 00:00.093111
> CF-RAY: 740068947daf5b28-IAD
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> 
> 
> Exited with code exit status 1
> CircleCI received exit code 1
> ```
> 
> Hope this failure is not related to this PR.

I don't think it's related. @rtburns-jpl to my untrained eye and shallow investigation, it looks like our CircleCI specfile needs to be updated to account for changes [here](https://repo.anaconda.com/pkgs/main/linux-64/)? What do you think? Whatever the case, I'll open a new issue to continue discussion there.

**Pull request merged**
