### PR TITLE
support python 3.8 by using future.__annotations__

### PR DESCRIPTION
**Pull request by scottstanie**
only a few typing hints had `list`, so this change is rather minimal

### CODE REVIEW

**Comment by scottstanie** [comment]
Any reason for holding off on merging this?

**Review by gshiroma — APPROVED** [review]
LGTM. Thank you for this update, @scottstanie

**Review by seongsujeong — APPROVED** [review]
LGTM. I might not be in the conversation, but can you briefly explain why the support for python 3.8 was necessary?

**Comment by scottstanie** [comment]
There wasn't any detailed conversation- it just seems like good practice to accommodate a python version that's not deprecated yet if there's no strong reason to move forward (like making heavy use of some feature that's not backward compatible). Doubly true for one like s1reader where python 3.8 incompatibility means all downstream packages can't use python 3.8 (like COMPASS, sweets, etc)

**Pull request merged**
