### PR TITLE
Beta release compass

### PR DESCRIPTION
**Pull request by seongsujeong**
This PR is to update the version number of the s1-reader for beta release of COMPASS.

### CODE REVIEW

**Comment by LiangJYu** [comment]
This is the [only relevant commit](https://github.com/opera-adt/s1-reader/pull/94/commits/071d18ca46b0cd964326c4c3367b322af7baa513)?

**Comment by seongsujeong** [comment]
> This is the [only relevant commit](https://github.com/opera-adt/s1-reader/pull/94/commits/071d18ca46b0cd964326c4c3367b322af7baa513)?

Yes. The fix on `s1_annotation.py` is in PR #92 and already merged.

**Review by LiangJYu — APPROVED** [review]
LGTM

**Review by vbrancat — APPROVED** [review]
LGTM

**Pull request merged**
